
apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketVersioning
metadata:
  name: backstage-0611-bucket-versioning
  labels:
    environment: dev
    managed-by: crossplane
spec:
  forProvider:
    region: us-east-1
    bucketRef:
      name: backstage-0611-bucket
    versioningConfiguration:
      - status: Enabled
  providerConfigRef:
    name: default
---
apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketServerSideEncryptionConfiguration
metadata:
  name: backstage-0611-bucket-sse
  labels:
    environment: dev
    managed-by: crossplane
spec:
  forProvider:
    region: us-east-1
    bucketRef:
      name: backstage-0611-bucket
    rule:
      - applyServerSideEncryptionByDefault:
          - sseAlgorithm: AES256
  providerConfigRef:
    name: default
